[package]
name = "validator"
version = "0.6.0"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]
license = "MIT"
description = "Common validation functions (email, url, length, ...) and trait"
homepage = "https://github.com/Keats/validator"
repository = "https://github.com/Keats/validator"
keywords = ["validation", "api", "validator"]

[dependencies]
url = "1"
regex = "0.2"
lazy_static = "0.2"
idna = "0.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
card-validate = "2.1"
phonenumber = { version = "0.1.0+8.7.0", optional = true }

[features]
phone = ["phonenumber"]
