[package]
name = "validator"
version = "0.10.1"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com"]
license = "MIT"
description = "Common validation functions (email, url, length, ...) and trait - to be used with `validator_derive`"
homepage = "https://github.com/Keats/validator"
repository = "https://github.com/Keats/validator"
keywords = ["validation", "api", "validator"]
edition = "2018"

[dependencies]
url = "2"
regex = "1"
lazy_static = "1"
idna = "0.2"
serde = "1"
serde_derive = "1"
serde_json = "1"
card-validate = { version = "2.1", optional = true }
phonenumber = { version = "0.2.0+8.7.0", optional = true }
unic-ucd-common = { version = "0.9.0", optional = true }

[features]
phone = ["phonenumber"]
card = ["card-validate"]
unic = ["unic-ucd-common"]