[package]
name = "validator_derive"
version = "0.10.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com"]
license = "MIT"
description = "Macros 1.1 implementation of #[derive(Validate)]"
homepage = "https://github.com/Keats/validator"
repository = "https://github.com/Keats/validator"
keywords = ["validation", "api", "validator"]
edition = "2018"

[lib]
proc-macro = true

[features]
phone = ["validator/phone"]
card = ["validator/card"]
unic = ["validator/unic"]

[dependencies]
syn = { version = "1", features = ["extra-traits"] }
quote = "1"
proc-macro2 = "1"
if_chain = "1"
validator = { version = "0.10", path = "../validator"}
regex = "1"
lazy_static = "1"

[dev-dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
compiletest_rs = "0.3"


