[package]
name = "validator_derive"
version = "0.6.5"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]
license = "MIT"
description = "Macros 1.1 implementation of #[derive(Validate)]"
homepage = "https://github.com/Keats/validator"
repository = "https://github.com/Keats/validator"
keywords = ["validation", "api", "validator"]

[lib]
proc-macro = true

[features]
phone = ["validator/phone"]
card = ["validator/card"]

[dependencies]
syn = { version = "0.13", features = ["extra-traits"] }
quote = "0.5"
if_chain = "0"
validator = { version = "0.6", path = "../validator"}

[dev-dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
compiletest_rs = "0.3"
regex = "0.2"
lazy_static = "1"


